format = """
$username\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$status\
$line_break\
$character"""

[username]
show_always = true
format = "[$user]($style) [@](bright-black) "

[directory]
style = "cyan"
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[#](green)"
error_symbol = "[#](red)"
vimcmd_symbol = "[❮](purple)"

[git_branch]
format = '\[[ $branch]($style)'
style = "purple"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-yellow"

[git_status]
disabled = false
format = '[[(*$conflicted$untracked$modified$staged$renamed$deleted)](red)($ahead_behind)]($style)\] '
style = "red"
ignore_submodules = true
untracked = ""

[cmd_duration]
format = "[$duration]($style) "
style = "bright-yellow"
min_time = 1_000
show_milliseconds = true

[status]
disabled = false
format = "[$status]($style) "
